encoding: "UTF-8"
lang: "en"
timezone: "Asia/Singapore"

title: "Remote theme example"
email: "info@mosquito.games"
description: "Rulebook for 1819 Singapore"

remote_theme: just-the-docs/just-the-docs
search_enabled: false
heading_anchors: true